
"""
EXAEPI AGENT PY

This module:
 * runs the ExaEpi agent in /tmp
 * redirects agent output to /tmp
 * extracts results from /tmp
 * returns results as Python string to workflow.

Our local tree looks like:

WORKDIR:
/tmp/USER/exaepi/
Contains input data decks and ExaEpi agent executable

RUNDIRS:
/tmp/USER/exaepi/runs/{0000001,0000002,0000003,...}

A rundir contains the input.cfg and agent.out
"""

import os, sys, traceback

import cfg_edit

VERBOSE = False

def run(idx, template_cfg, seed, urbanpop, cases, params):
    """
    Runs ExaEpi agent in local rundir and extract resulting data
    idx:          int index
    template_cfg: string filename of original cfg (usually in /tmp)
    seed:         int random seed
    urbanpop:     string of urbanpop basename, assumed in workdir
    cases:        string of cases basename, assumed in workdir
    params:       dict of other parameters to modify
    return:       string of JSON containing important result values
    """

    user      = os.getenv("USER")
    workdir   = f"/tmp/{user}/exaepi"
    rundir    = f"{workdir}/runs/{idx:07d}"
    # ExaEpi input file to generate and run:
    input_cfg = f"{rundir}/input.cfg"
    # stdout/stderr from ExaEpi agent:
    agent_out = f"{rundir}/agent.out"

    verbose("exaepi_agent: template_cfg: " + template_cfg)
    verbose("exaepi_agent: input_cfg:    " + input_cfg)

    os.makedirs(rundir, exist_ok=True)

    cfg_id = cfg_edit_checked(template_cfg, rundir, seed,
                              f"{workdir}/{urbanpop}",
                              f"{workdir}/{cases}",
                              params, input_cfg)

    run_exaepi(workdir, rundir, input_cfg, agent_out)

    # result: dict of JSON
    result = get_results(agent_out)
    # Add some additional metadata:
    # idx: a unique integer generated by the workflow:
    result["idx"]    = idx
    # cfg_id: an integer stored in the input cfg file (or None):
    result["cfg_id"] = cfg_id
    # params_id: an integer stored in the params specification:
    if "params_id" in params:
        result["params_id"] = params["params_id"]
    # the random seed used:
    result["seed"]   = seed

    # Convert dict of JSON to string for Swift/T:
    s = format_json(result)
    return s


def cfg_edit_checked(template_cfg, rundir, seed, urbanpop, cases,
                     params, input_cfg):
    """ Do cfg_edit, crash on Exceptions """
    try:
        cfg_id = cfg_edit.process(template_cfg, rundir, seed,
                                  urbanpop, cases, params, input_cfg)
    except Exception as e:
        print("exaepi_agent.run(): Exception in cfg_edit!")
        print("exaepi_agent.run(): " + str(e))
        print("", flush=True)
        t = traceback.format_exc()
        print(t)
        print("", flush=True)
        exit(1)
    return cfg_id


def run_csv_lines(idx, template_cfg, seed, urbanpop, cases, lines):
    """
    Runs ExaEpi agent in local rundir and extract data
    See run() for most parameters
    params:       CSV lines of parameters to modify
    return:       string of JSON containing key output values
    """

    params = lines2params(lines)
    return run(idx, template_cfg, seed, urbanpop, cases, params)


def run_str_dict(idx, template_cfg, seed,
                 urbanpop, cases, str_dict):
    """
    Runs ExaEpi agent in local rundir and extract data
    See run() for most parameters
    str_dict:  string of JSON dict with more parameters for eval()
    return:    string of JSON containing key output values
    """

    params = eval(str_dict)
    return run(idx, template_cfg, seed, urbanpop, cases, params)


def lines2params(lines):
    """
    Parse the CSV lines into a dict
    lines: 2 lines separated by NL, a CSV header and the CSV data
    """
    import csv
    from io import StringIO
    # pair = lines.split('\n')
    # assert(len(pair) == 2)
    fp = StringIO(lines)
    reader = csv.reader(fp)
    data_list = list(reader)
    assert len(data_list) == 2
    # headers = pair[0].split(',')
    # values  = pair[1].split(',')
    (headers, values) = data_list
    assert len(headers) == len(values), ("mismatch: headers=%i values=%i" %
                                         (len(headers), len(values)))
    params = {}
    # print("headers: " + str(headers))
    for header, value in zip(headers, values):
        params[header] = value

    return params


def run_exaepi(workdir, rundir, input_cfg, agent_out):
    import subprocess
    cmd = ["mpiexec", workdir + "/agent", input_cfg]
    with open(agent_out, "w") as fp:
        child = subprocess.run(cmd,
                               cwd = rundir,
                               stdout=fp,
                               stderr=subprocess.STDOUT)
    if child.returncode != 0:
        print("exaepi_agent.run_exaepi(): agent exit code: %i" %
              child.returncode,
              flush=True)
        exit(1)
    # print("ExaEpi agent OK.", flush=True)


def get_results(agent_out):
    """ Read ExaEpi agent output and stuff into a JSON string """
    day_final = 0
    infecteds = []
    deaths    = []
    with open(agent_out, "r") as fp:
        while True:
            line = fp.readline()
            if line == "": break
            if line.startswith("[Day "):
                tokens   = line.split(" ")
                day      = int(tokens[1])
                # Drop trailing semicolon:
                infected = int(tokens[5][0:-1])
                dead     = int(tokens[7])
                day_final = day
                infecteds.append(infected)
                deaths.append(dead)
    return {"day_final": day_final,
            "infected" : infecteds,
            "deaths"   : deaths}


def format_json(D):
    """ Format nicely in JSON """
    import pprint
    result = pprint.pformat(D) + "\n\n"
    return result


def run_fake(idx, template_cfg, seed, urbanpop, cases, params):
    """ TODO: Generate fake ExaEpi output """
    pass


def verbose(msg):
    if VERBOSE:
        print(msg, flush=True)
