#!/bin/zsh
set -eu

THIS=${0:h:A}
source $THIS/../common/tools.zsh

args SET N - ${*}

show N

exists ${SET}_params.csv

OUTPUT=${SET}_params_$N.csv
head -$[N+1] ${SET}_params.csv > $OUTPUT

{
  printf "lines "
  wc -l < $OUTPUT
  printf "size  "
  du -h --apparent-size $OUTPUT
} | column -t
