#!/bin/zsh
set -e

# LOG2PQT

# Get the directory where this script is located
THIS="${0:h:A}"
JAR_FILE="$THIS/target/log-to-parquet-1.0-jar-with-dependencies.jar"

# Build if jar doesn't exist
if [[ ! -f "$JAR_FILE" ]]
then
  print "Building project..."
  cd "$THIS"
  mvn clean package -DskipTests -q
  cd - > /dev/null
fi

# The command line belongs to the Java layer, which reports on it
java -cp "$JAR_FILE" LogToParquet "$@"

# Local Variables:
# sh-basic-offset: 2
# mode: sh
# End:
