#!/bin/zsh
set -eu

THIS=${0:h:A}
source $THIS/../common/tools.zsh

zparseopts -D -E n=N
args DIR - ${*}

if [[ ! -d $DIR ]] abort "No DIR=$DIR"

printf "JOB:    "
cat $DIR/jobid.txt | head -c 7
print

$THIS/log-size $N 64 $DIR

if (( ${#N} )) {
  print "AMReX finalized"
  find $DIR/runs -name agent.out | \
    xargs -n 4 cat               | \
    grep -c "AMReX.*finalized"
}

if ! grep "Elapsed Time" $DIR/output.txt
then
  abort "No Elapsed Time!"
fi
