#!/bin/zsh
set -eu

THIS=${0:h:A}
source $THIS/../common/tools.zsh

echo -- ARGS ${*}
zparseopts -D -E n=N
echo -- ARGS ${*}
args DIR - ${*}

if [[ ! -d $DIR ]] abort "No DIR=$DIR"

printf "JOB:    "
cat $DIR/jobid.txt | head -c 7
print

$THIS/log-size $N 64 $DIR

grep "Elapsed Time2" $DIR/output.txt
