#!/bin/zsh
set -eu

# SHOW_PQT
# Wrapper for show_pqt.py

# Get the directory where this script is located
THIS="${0:h:A}"

python3 "$THIS/show_pqt.py" "$@"

# Local Variables:
# sh-basic-offset: 2
# mode: sh
# End:
